%% JCAS_GeneratePubFigs.m
%  Generate all 10 publication figures from CSV output files.
%  Figures are exported as JPG (300 dpi) to the 'figures' folder.
%
%  Input  : JCAS_Results/ folder containing CSV01..CSV11 files
%           (generated by JCASFasaIMultistaticwith5GAAStandard.m or
%            JCASFasaIMultistaticwith5GAAStandard_LoopingExperiment.m)
%  Output : figures/PubFig1_Pareto.jpg  .. figures/PubFig10_PerNode_RMSE.jpg
%
%  Galih Nugraha Nurkahfi -- PR Telekomunikasi, BRIN
%  Version: 1.0

clear; clc; close all;

% ── Paths ────────────────────────────────────────────────────────────────────
csv_dir  = 'JCAS_Results';          % folder containing CSV files
out_dir  = 'figures';               % output folder for JPG
suffix   = '_Primary_BW20MHz_6nodes_ModeC';  % looping experiment suffix
                                    % set to '' if using standalone run

if ~exist(out_dir,'dir'); mkdir(out_dir); end

% ── Colour palette (consistent across all figures) ───────────────────────────
C.static  = [0.122 0.471 0.706];   % blue
C.wf      = [1.000 0.498 0.055];   % orange
C.adapt   = [0.173 0.627 0.173];   % green
C.ql      = [0.839 0.153 0.157];   % red
C.sarsa   = [0.580 0.404 0.741];   % purple
C.bandit  = [0.549 0.337 0.294];   % brown
C.slr     = [0.200 0.627 0.173];   % green for SLR lines
C.fail    = [0.839 0.153 0.157];   % red for SLR fail lines
colors    = [C.static; C.wf; C.adapt; C.ql; C.sarsa; C.bandit];
strat_names = {'Static','Water-Fill','Adaptive','Q-Learning','SARSA','Greedy Bandit'};
markers   = {'o','s','^','d','v','p'};

% ── Helper: export figure ─────────────────────────────────────────────────────
function export_fig(fh, out_dir, fname)
    set(fh,'PaperPositionMode','auto','Color','w');
    exportgraphics(fh, fullfile(out_dir,[fname '.jpg']), ...
        'Resolution',300,'BackgroundColor','white');
    fprintf('[EXPORT] %s.jpg saved\n', fname);
end

% ── Helper: read primary CSV ──────────────────────────────────────────────────
function T = read_csv(csv_dir, num, suffix)
    fname = fullfile(csv_dir, sprintf('CSV%02d_%s%s.csv', num, ...
        csv_label(num), suffix));
    if ~exist(fname,'file')
        % try without suffix
        fname = fullfile(csv_dir, sprintf('CSV%02d_%s.csv', num, csv_label(num)));
    end
    if ~exist(fname,'file')
        warning('CSV not found: %s', fname);
        T = table(); return;
    end
    % Skip header rows until we find the data header
    raw = readlines(fname);
    for i = 1:length(raw)
        if contains(raw(i),'Strategy') || contains(raw(i),'SNR_dB') || ...
           contains(raw(i),'BW_MHz')   || contains(raw(i),'Node')   || ...
           contains(raw(i),'Episode')  || contains(raw(i),'w_c')    || ...
           contains(raw(i),'Config')   || contains(raw(i),'Scenario')
            T = readtable(fname,'NumHeaderLines',i-1,'VariableNamingRule','preserve');
            return;
        end
    end
    T = readtable(fname,'VariableNamingRule','preserve');
end

function lbl = csv_label(num)
    labels = {'Paper_Summary','Pareto_Sweep','Pd_vs_SNR','PerNode_RMSE', ...
              'BW_Comparison','RL_Training','Statistical_Significance', ...
              'Sensitivity_Analysis','Convergence','Ablation','Generalization'};
    lbl = labels{num};
end

fprintf('\n=== JCAS Publication Figure Generator ===\n');
fprintf('CSV dir : %s\n', csv_dir);
fprintf('Out dir : %s\n\n', out_dir);

% ═══════════════════════════════════════════════════════════════════════════
%  PubFig2 — Bar chart: Capacity per strategy (primary scenario)
%  Source : CSV01_Paper_Summary_Primary_BW20MHz_6nodes_ModeC.csv
% ═══════════════════════════════════════════════════════════════════════════
T1 = read_csv(csv_dir, 1, suffix);
if ~isempty(T1)
    fh = figure('Units','centimeters','Position',[2 2 18 10],'Color','w');
    cap = T1.Cap_Mbps;
    b = bar(cap, 0.6, 'FaceColor','flat');
    for k = 1:length(cap)
        b.CData(k,:) = colors(k,:);
    end
    hold on;
    yline(0.2,'--','Color',C.slr,'LineWidth',1.5,'Label','5GAA SLR 0.2 Mbps');
    xticks(1:6); xticklabels(strat_names);
    xlabel('Allocation Strategy','FontSize',10);
    ylabel('Shannon Capacity (Mbps)','FontSize',10);
    title('Spectral Efficiency per Strategy — Primary Scenario (6 nodes, 20 MHz, Mode C)',...
          'FontSize',10,'FontWeight','normal');
    % value labels on bars
    for k = 1:length(cap)
        text(k, cap(k)+1, sprintf('%.1f',cap(k)), ...
             'HorizontalAlignment','center','FontSize',8,'Color',colors(k,:));
    end
    grid on; box on; ylim([0 max(cap)*1.15]);
    legend(strat_names,'Location','northeast','FontSize',8,'NumColumns',2);
    export_fig(fh, out_dir, 'PubFig2_BarKPI');
end

% ═══════════════════════════════════════════════════════════════════════════
%  PubFig1 — Pareto frontier: Capacity vs RMSE
%  Source : CSV02_Pareto_Sweep_Primary_BW20MHz_6nodes_ModeC.csv
% ═══════════════════════════════════════════════════════════════════════════
T2 = read_csv(csv_dir, 2, suffix);
if ~isempty(T2)
    fh = figure('Units','centimeters','Position',[2 2 18 11],'Color','w');
    strats_u = unique(T2.Strategy,'stable');
    hold on;
    h = gobjects(length(strats_u),1);
    for si = 1:length(strats_u)
        idx = strcmp(T2.Strategy, strats_u{si});
        rm  = T2.RMSE_m(idx);
        cp  = T2.Cap_Mbps(idx);
        col = colors(si,:);
        if length(unique(rm)) == 1  % RL: single point
            h(si) = scatter(rm(1), cp(1), 80, col, markers{si}, ...
                            'filled','LineWidth',1.5,'DisplayName',strats_u{si});
        else
            h(si) = plot(rm, cp, '-','Color',col,'LineWidth',1.8, ...
                         'Marker',markers{si},'MarkerSize',5,...
                         'MarkerFaceColor',col,'DisplayName',strats_u{si});
        end
    end
    xline(1.5,'--','Color',C.slr,'LineWidth',1.5,'Label','5GAA RMSE 1.5 m');
    xlabel('EKF RMSE (m)','FontSize',10);
    ylabel('Capacity (Mbps)','FontSize',10);
    title('Communication-Sensing Pareto Frontier — Primary Scenario',...
          'FontSize',10,'FontWeight','normal');
    legend(h,'Location','northwest','FontSize',8,'NumColumns',2);
    grid on; box on; set(gca,'XScale','log');
    export_fig(fh, out_dir, 'PubFig1_Pareto');
end

% ═══════════════════════════════════════════════════════════════════════════
%  PubFig3 — Pd vs SNR (all scenarios)
%  Source : CSV03_Pd_vs_SNR_*.csv
% ═══════════════════════════════════════════════════════════════════════════
scen_files = {
    '_Primary_BW20MHz_6nodes_ModeC',  'Primary 6-node 20MHz';
    '',                                '8-node 20MHz ModeC';
    '_BWsweep_BW10MHz_6nodes_ModeC',  '10MHz 6-node ModeC';
    '_BWsweep_BW40MHz_6nodes_ModeC',  '40MHz 6-node ModeC';
    '_Density_BW20MHz_4nodes_ModeC',  '4-node ModeC';
    '_Density_BW20MHz_10nodes_ModeC', '10-node ModeC';
    '_Topology_BW20MHz_6nodes_ModeB', '6-node ModeB';
    '_Topology_BW20MHz_6nodes_Mono',  '6-node Mono';
};
fh = figure('Units','centimeters','Position',[2 2 18 11],'Color','w');
hold on;
scen_colors = lines(size(scen_files,1));
h3 = gobjects(size(scen_files,1),1);
for si = 1:size(scen_files,1)
    sfx = scen_files{si,1};
    fname = fullfile(csv_dir, ['CSV03_Pd_vs_SNR' sfx '.csv']);
    if ~exist(fname,'file'); continue; end
    raw = readlines(fname);
    for i=1:length(raw)
        if contains(raw(i),'SNR_dB')
            T3 = readtable(fname,'NumHeaderLines',i-1,'VariableNamingRule','preserve');
            break;
        end
    end
    if exist('T3','var') && ~isempty(T3)
        h3(si) = plot(T3.SNR_dB, T3.Pd_pct, '-o', ...
                      'Color',scen_colors(si,:),'LineWidth',1.5,...
                      'MarkerSize',4,'MarkerFaceColor',scen_colors(si,:),...
                      'DisplayName',scen_files{si,2});
    end
    clear T3;
end
yline(95,'--r','LineWidth',2,'Label','5GAA SLR: Pd \geq 95%');
xlabel('SNR (dB)','FontSize',10);
ylabel('Detection Probability P_d (%)','FontSize',10);
title('Detection Probability vs. SNR — All Scenarios','FontSize',10,'FontWeight','normal');
ylim([0 110]); xlim([-6 26]); grid on; box on;
valid = arrayfun(@(x) isvalid(x), h3);
legend(h3(valid),'Location','northwest','FontSize',7,'NumColumns',2);
export_fig(fh, out_dir, 'PubFig3_PdBER_vs_SNR');

% ═══════════════════════════════════════════════════════════════════════════
%  PubFig4 — BW Comparison: RMSE vs Bandwidth
%  Source : CSV05_BW_Comparison_*.csv
% ═══════════════════════════════════════════════════════════════════════════
bw_scens = {
    suffix,                            '8-node (primary)';
    '_Primary_BW20MHz_6nodes_ModeC',  'Primary 6-node';
    '_Density_BW20MHz_4nodes_ModeC',  '4-node ModeC';
    '_Density_BW20MHz_10nodes_ModeC', '10-node ModeC';
    '_Topology_BW20MHz_6nodes_ModeB', 'ModeB 6-node';
    '_Topology_BW20MHz_6nodes_Mono',  'Mono 6-node';
};
fh = figure('Units','centimeters','Position',[2 2 18 11],'Color','w');
hold on;
bw_colors = lines(size(bw_scens,1));
h4 = gobjects(size(bw_scens,1),1);
for si = 1:size(bw_scens,1)
    sfx = bw_scens{si,1};
    fname = fullfile(csv_dir, ['CSV05_BW_Comparison' sfx '.csv']);
    if ~exist(fname,'file'); continue; end
    raw = readlines(fname);
    for i=1:length(raw)
        if contains(raw(i),'BW_MHz')
            T5 = readtable(fname,'NumHeaderLines',i-1,'VariableNamingRule','preserve');
            break;
        end
    end
    if exist('T5','var') && ~isempty(T5)
        h4(si) = plot(T5.BW_MHz, T5.RMSE_approx_m, '-s',...
                      'Color',bw_colors(si,:),'LineWidth',1.8,...
                      'MarkerSize',6,'MarkerFaceColor',bw_colors(si,:),...
                      'DisplayName',bw_scens{si,2});
    end
    clear T5;
end
yline(1.5,'--','Color',C.slr,'LineWidth',2,'Label','5GAA SLR: RMSE \leq 1.5 m');
xlabel('System Bandwidth (MHz)','FontSize',10);
ylabel('EKF RMSE (m)','FontSize',10);
title('EKF RMSE vs. Bandwidth — Topology and Density Comparison',...
      'FontSize',10,'FontWeight','normal');
set(gca,'XTick',[10 20 40]);
grid on; box on;
valid = arrayfun(@(x) isvalid(x), h4);
legend(h4(valid),'Location','northeast','FontSize',8);
export_fig(fh, out_dir, 'PubFig4_BW_Comparison');

% ═══════════════════════════════════════════════════════════════════════════
%  PubFig5 — RL Convergence (moving average reward)
%  Source : CSV09_Convergence_Primary_BW20MHz_6nodes_ModeC.csv
% ═══════════════════════════════════════════════════════════════════════════
fname9 = fullfile(csv_dir, ['CSV09_Convergence' suffix '.csv']);
if ~exist(fname9,'file')
    fname9 = fullfile(csv_dir, 'CSV09_Convergence_Primary_BW20MHz_6nodes_ModeC.csv');
end
if exist(fname9,'file')
    raw = readlines(fname9);
    for i=1:length(raw)
        if contains(raw(i),'Episode')
            T9 = readtable(fname9,'NumHeaderLines',i-1,'VariableNamingRule','preserve');
            break;
        end
    end
    if exist('T9','var') && ~isempty(T9)
        fh = figure('Units','centimeters','Position',[2 2 18 10],'Color','w');
        hold on;
        rl_names = {'Q-Learning','SARSA','Greedy Bandit'};
        rl_cols  = [C.ql; C.sarsa; C.bandit];
        col_names = T9.Properties.VariableNames;
        ep = T9.(col_names{1});
        for ai = 1:3
            cn = col_names{ai+1};
            plot(ep, T9.(cn), '-', 'Color',rl_cols(ai,:),...
                 'LineWidth',1.5,'DisplayName',rl_names{ai});
        end
        xlabel('Episode','FontSize',10);
        ylabel('Mean Reward (100-ep moving avg)','FontSize',10);
        title('RL Convergence — Primary Scenario (3000 Episodes)',...
              'FontSize',10,'FontWeight','normal');
        legend('Location','southeast','FontSize',9);
        grid on; box on; xlim([0 3000]);
        export_fig(fh, out_dir, 'PubFig5_RL_Convergence');
    end
end

% ═══════════════════════════════════════════════════════════════════════════
%  PubFig6 — Bootstrap CI
%  Source : CSV07_Statistical_Significance_Primary_BW20MHz_6nodes_ModeC.csv
% ═══════════════════════════════════════════════════════════════════════════
fname7 = fullfile(csv_dir, ['CSV07_Statistical_Significance' suffix '.csv']);
if ~exist(fname7,'file')
    fname7 = fullfile(csv_dir,'CSV07_Statistical_Significance_Primary_BW20MHz_6nodes_ModeC.csv');
end
if exist(fname7,'file')
    raw = readlines(fname7);
    for i=1:length(raw)
        if contains(raw(i),'Strategy')
            T7 = readtable(fname7,'NumHeaderLines',i-1,'VariableNamingRule','preserve');
            break;
        end
    end
    if exist('T7','var') && ~isempty(T7)
        fh = figure('Units','centimeters','Position',[2 2 18 10],'Color','w');
        hold on;
        n = height(T7);
        for k = 1:n
            col = colors(k,:);
            mn  = T7.Mean_Cap_Mbps(k);
            cil = T7.CI_Low95_Mbps(k);
            cih = T7.CI_High95_Mbps(k);
            % CI bar
            plot([k k],[cil cih],'-','Color',col,'LineWidth',3);
            % whisker caps
            plot([k-0.15 k+0.15],[cil cil],'-','Color',col,'LineWidth',2);
            plot([k-0.15 k+0.15],[cih cih],'-','Color',col,'LineWidth',2);
            % mean marker
            scatter(k, mn, 60, col, 'd','filled');
            text(k, mn+3, sprintf('%.1f',mn),...
                 'HorizontalAlignment','center','FontSize',8,'Color',col);
        end
        xticks(1:n);
        xticklabels(strat_names(1:n));
        xlabel('Strategy','FontSize',10);
        ylabel('Capacity (Mbps)','FontSize',10);
        title('Bootstrap 95% CI (BCa, n=1000 resamples) — Primary Scenario',...
              'FontSize',10,'FontWeight','normal');
        text(0.5, 0.95, 'p = 1.0 vs Static for all strategies (deterministic policy outcomes)',...
             'Units','normalized','FontSize',8,'Color','k',...
             'HorizontalAlignment','left','VerticalAlignment','top',...
             'BackgroundColor',[1 1 0.8],'EdgeColor',[0.8 0.8 0]);
        grid on; box on; ylim([0 130]);
        export_fig(fh, out_dir, 'PubFig6_Bootstrap_CI');
    end
end

% ═══════════════════════════════════════════════════════════════════════════
%  PubFig7 — Sensitivity: QL vs SARSA across weight configs
%  Source : CSV08_Sensitivity_Analysis_Primary_BW20MHz_6nodes_ModeC.csv
% ═══════════════════════════════════════════════════════════════════════════
fname8 = fullfile(csv_dir, ['CSV08_Sensitivity_Analysis' suffix '.csv']);
if ~exist(fname8,'file')
    fname8 = fullfile(csv_dir,'CSV08_Sensitivity_Analysis_Primary_BW20MHz_6nodes_ModeC.csv');
end
if exist(fname8,'file')
    raw = readlines(fname8);
    for i=1:length(raw)
        if contains(raw(i),'w_c')
            T8 = readtable(fname8,'NumHeaderLines',i-1,'VariableNamingRule','preserve');
            break;
        end
    end
    if exist('T8','var') && ~isempty(T8)
        fh = figure('Units','centimeters','Position',[2 2 18 10],'Color','w');
        wc = T8.w_c;
        hold on;
        plot(wc, T8.QL_Cap_Mbps, '-o','Color',C.ql,'LineWidth',1.8,...
             'MarkerSize',6,'MarkerFaceColor',C.ql,'DisplayName','Q-Learning');
        plot(wc, T8.SARSA_Cap_Mbps, '-s','Color',C.sarsa,'LineWidth',1.8,...
             'MarkerSize',6,'MarkerFaceColor',C.sarsa,'DisplayName','SARSA');
        xlabel('Communication Weight w_c  (w_s = 0.9 - w_c, w_d = 0.1)','FontSize',10);
        ylabel('Capacity (Mbps)','FontSize',10);
        title('Reward Weight Sensitivity — Q-Learning vs SARSA (Primary Scenario)',...
              'FontSize',10,'FontWeight','normal');
        legend('Location','northwest','FontSize',9);
        xticks(wc); grid on; box on;
        export_fig(fh, out_dir, 'PubFig7_Sensitivity_Weight');
    end
end

% ═══════════════════════════════════════════════════════════════════════════
%  PubFig8 — Ablation study (grouped bar)
%  Source : CSV10_Ablation_*.csv  (4 scenarios)
% ═══════════════════════════════════════════════════════════════════════════
abl_files = {
    suffix,                            '8-node 20MHz';
    '_Primary_BW20MHz_6nodes_ModeC',  'Primary 6-node';
    '_BWsweep_BW40MHz_6nodes_ModeC',  '40MHz 6-node';
    '_Density_BW20MHz_10nodes_ModeC', '10-node ModeC';
};
abl_data = zeros(4, size(abl_files,1));
cfg_names = {'Full','No Detect','No Comm','No Sense'};
for si = 1:size(abl_files,1)
    sfx = abl_files{si,1};
    fname = fullfile(csv_dir, ['CSV10_Ablation' sfx '.csv']);
    if ~exist(fname,'file'); continue; end
    raw = readlines(fname);
    for i=1:length(raw)
        if contains(raw(i),'Configuration')
            Ta = readtable(fname,'NumHeaderLines',i-1,'VariableNamingRule','preserve');
            break;
        end
    end
    if exist('Ta','var') && ~isempty(Ta)
        abl_data(:,si) = Ta.QL_Cap_Mbps(1:4);
    end
    clear Ta;
end
fh = figure('Units','centimeters','Position',[2 2 18 10],'Color','w');
b8 = bar(abl_data, 0.75);
abl_colors = lines(size(abl_files,1));
for k = 1:size(abl_files,1)
    b8(k).FaceColor = abl_colors(k,:);
end
xticks(1:4); xticklabels(cfg_names);
xlabel('Reward Configuration','FontSize',10);
ylabel('Q-Learning Capacity (Mbps)','FontSize',10);
title('Ablation Study: Effect of Reward Component Removal',...
      'FontSize',10,'FontWeight','normal');
legend(abl_files(:,2),'Location','northeast','FontSize',8);
grid on; box on;
export_fig(fh, out_dir, 'PubFig8_Ablation');

% ═══════════════════════════════════════════════════════════════════════════
%  PubFig9 — Generalization heatmap
%  Source : CSV11_Generalization_*.csv
% ═══════════════════════════════════════════════════════════════════════════
gen_files = {
    '_Primary_BW20MHz_6nodes_ModeC',  'Primary';
    '_Topology_BW20MHz_6nodes_ModeB', 'ModeB';
    '_Topology_BW20MHz_6nodes_Mono',  'Mono';
    '_BWsweep_BW10MHz_6nodes_ModeC',  '10 MHz';
    '_BWsweep_BW40MHz_6nodes_ModeC',  '40 MHz';
};
gen_mat = zeros(5,3);
den_names = {'Low','Medium','High'};
for ri = 1:size(gen_files,1)
    fname = fullfile(csv_dir, ['CSV11_Generalization' gen_files{ri,1} '.csv']);
    if ~exist(fname,'file'); continue; end
    raw = readlines(fname);
    for i=1:length(raw)
        if contains(raw(i),'Scenario')
            Tg = readtable(fname,'NumHeaderLines',i-1,'VariableNamingRule','preserve');
            break;
        end
    end
    if exist('Tg','var') && ~isempty(Tg) && height(Tg)>=3
        gen_mat(ri,:) = Tg.Cap_Mbps(1:3)';
    end
    clear Tg;
end
fh = figure('Units','centimeters','Position',[2 2 16 10],'Color','w');
imagesc(gen_mat);
colormap(flipud(winter));
cb = colorbar; cb.Label.String = 'Capacity (Mbps)'; cb.Label.FontSize=9;
xticks(1:3); xticklabels(den_names);
yticks(1:5); yticklabels(gen_files(:,2));
xlabel('Node Density','FontSize',10);
ylabel('Topology / Bandwidth','FontSize',10);
title('Cross-Scenario Generalisation: Q-Learning Capacity (Mbps)',...
      'FontSize',10,'FontWeight','normal');
% value labels in cells
for ri=1:5
    for ci=1:3
        text(ci,ri,sprintf('%.1f',gen_mat(ri,ci)),...
             'HorizontalAlignment','center','FontSize',9,...
             'FontWeight','bold','Color','k');
    end
end
export_fig(fh, out_dir, 'PubFig9_Generalization');

% ═══════════════════════════════════════════════════════════════════════════
%  PubFig10 — Per-Node EKF RMSE
%  Source : CSV04_PerNode_RMSE.csv  (standalone or primary suffix)
% ═══════════════════════════════════════════════════════════════════════════
fname4 = fullfile(csv_dir, 'CSV04_PerNode_RMSE.csv');
if ~exist(fname4,'file')
    fname4 = fullfile(csv_dir, ['CSV04_PerNode_RMSE' suffix '.csv']);
end
if exist(fname4,'file')
    raw = readlines(fname4);
    for i=1:length(raw)
        if contains(raw(i),'Node')
            T4 = readtable(fname4,'NumHeaderLines',i-1,'VariableNamingRule','preserve');
            break;
        end
    end
    if exist('T4','var') && ~isempty(T4)
        % Remove MEAN row if present
        T4 = T4(~isnan(T4.Node),:);
        n4 = height(T4);
        fh = figure('Units','centimeters','Position',[2 2 18 10],'Color','w');
        hold on;
        x = 1:n4;
        % Raw RMSE bars
        bar(x - 0.2, T4.RawRMSE_m, 0.35, 'FaceColor',[0.68 0.78 0.91],...
            'EdgeColor','none','DisplayName','Raw RMSE');
        % EKF RMSE bars coloured by pass/fail
        pass5g = strcmp(T4.Pass_5GAA,'PASS');
        for k=1:n4
            col = C.slr; if ~pass5g(k); col = C.fail; end
            bar(k+0.2, T4.EKFRMSE_m(k), 0.35,'FaceColor',col,'EdgeColor','none');
            text(k+0.2, T4.EKFRMSE_m(k)+0.1, sprintf('%.2f',T4.EKFRMSE_m(k)),...
                 'HorizontalAlignment','center','FontSize',7,'Color',col);
        end
        yline(1.5,'--','Color',C.slr,'LineWidth',1.5,...
              'Label','5GAA SLR 1.5 m','LabelHorizontalAlignment','left');
        % Node labels
        node_lbls = arrayfun(@(k) sprintf('N%d\n%s',T4.Node(k),T4.Type{k}), ...
                             1:n4,'UniformOutput',false);
        xticks(1:n4); xticklabels(node_lbls);
        xlabel('Node','FontSize',10);
        ylabel('RMSE (m)','FontSize',10);
        title('Per-Node EKF RMSE vs. Raw RMSE','FontSize',10,'FontWeight','normal');
        % Manual legend
        hp(1) = bar(nan, nan, 'FaceColor',[0.68 0.78 0.91],'EdgeColor','none');
        hp(2) = bar(nan, nan, 'FaceColor',C.slr,'EdgeColor','none');
        hp(3) = bar(nan, nan, 'FaceColor',C.fail,'EdgeColor','none');
        legend(hp,{'Raw RMSE','EKF RMSE (PASS)','EKF RMSE (FAIL)'},...
               'Location','northeast','FontSize',8);
        grid on; box on;
        export_fig(fh, out_dir, 'PubFig10_PerNode_RMSE');
    end
end

fprintf('\n=== All figures done. Check folder: %s ===\n', out_dir);
